services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "elaw@2025"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Docker/Web.Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      ASPNETCORE_ENVIROMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;DataBase=StarWarsDb;UserId=sa;Password=elaw@2025;TrustServerCertificate=true"
volumes:
  rabbitmq_data:
  sql_data: